name: Validate Issues To Post

on:
  issues:
    types:
      - opened
      - edited
      - transferred
      - reopened
      - labeled
  push:
    branches:
      - master

jobs:
  validate:
    name: Run validate_issues.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          python -m pipenv install
      - name: Validate
        run: pipenv run python validate_issues.py
        env:
          GITHUBREPO: ${{ secrets.GitHubRepo }}
